### ISSUE TITLE
Resolve property dosen't work for edit in widget configuration

### ISSUE THREAD

**Issue by adamlepkowski** [angular-dashboard-framework/angular-dashboard-framework#14]
I'm creating my custom widget for retriving information from jira system. I want to set resolve property for widget edit configuration, but when I do it I get the following exception: " [$injector:unpr] Unknown provider: abcProvider <- abc"

My code widget looks like here(it's a draft version:P): 

``` javascript
'use strict';
angular.module('sample.widgets.sprintdetails', ['adf.provider'])
  .value('sprintdetailsServiceUrl', 'jiraurl')
  .config(function (dashboardProvider) {
      dashboardProvider
        .widget('sprintdetails', {
            title: 'Sprint details',
            description: 'Displays a current sprint general information',
            templateUrl: 'widgets/sprintdetails/sprintdetails.html',
            controller: 'sprintdetailsCtrl',
            edit: {
                templateUrl: 'widgets/sprintdetails/edit.html',
                reload: false,
                controller: 'sprintdetailsEditCtrl',
                resolve: {
                    abc: function (jiraService, sprintdetailsServiceUrl) {
                        return jiraService.get(sprintdetailsServiceUrl);
                    }
                }
            }
        });
  })
  .service('jiraService', function ($q, $http) {
      return {
          get: function (url) {
              var deferred = $q.defer();
              $http.get(url)
                .success(function (data, status, headers, config) {
                    if (data) {
                        deferred.resolve(data);
                    } else {
                        deferred.reject();
                    }
                })
                .error(function (data, status, headers, config) {
                    deferred.reject();
                });
              return deferred.promise;
          }
      };
  })
  .controller('sprintdetailsCtrl', function ($scope, config) {      
  })
  .controller('sprintdetailsEditCtrl', function ($scope, abc) {
      $scope.abc = abc;
  });
```

**Comment by todeia** [comment]
Hello.
I'm trying to create my widget.

<pre>  'use strict';
  angular.module('widgets.list', ['adf.provider'])
    .config(function(dashboardProvider){
      dashboardProvider
        .widget('list', {
          title: 'table Title',
          description: 'Description of table',
          controller: 'tableController',
          templateUrl: 'views/list.html',
          resolve: {
            tabledata: function(tableService){
              return tableService.get();
            }
          }
        });
    })
    .service('tableService', function($q, $http, $timeout){
      return {
        get: function(){
          var deferred = $q.defer();
          $timeout(function () {
            deferred.resolve([1, 2, 3, 4, 5]);
          }, 1000);
          return deferred.promise;
        }
      };
    })
    .controller('tableController', function($scope, tabledata){
      $scope.data = tabledata;
    });
</pre>

In development environment works, but when I create the build, the build does not work.
Error: [$injector:unpr] Unknown provider: aProvider <- a

The problem will be my widget?

Thanks.
