### ISSUE TITLE
Duplicate Widget Ids after loading from storage causing issues with ngRepeat

### ISSUE THREAD

**Issue by codedward** [angular-dashboard-framework/angular-dashboard-framework#146]
I hooked things up to save the dashboard model to our database. When I reload the dashboard and add new widgets and then move things around, sometimes the Widgets disappear.

I traced it back to the id() generator on the dashboard provider -- The new ids generated always start at 0. My repro steps on my implementation:

1. Create a new, empty dashboard
2. Add two widgets (with ids of 0 and 1)
3. Save
4. Reload
5. Move the widgets (ids of 0 and 1) to a different column
6. Add a new widget (also has id of 0)
7. Move all the widgets to the third column
8. Get console errors in ngRepeat in dashboard-column about needing a unique id

Please note that I have been unable to reproduce in the demo page, so it may have something to do with how I'm persisting the dashboard across reloads.

To fix it, I changed the line in `src/scripts/provider.js`
    `return ++cid;`
to 
    `return (Math.random() * 100000) | 0;`

I can make a pull request if you'd like, but am interested if there is a better solution.

**Comment by sdorra** [comment]
You are right we need a real unique id for widget or we should stop to store widget ids in the model, but i think the Math.random is not safe enough.

**Comment by sdorra** [comment]
I think we could add the timestamp to the id:

```javascript
return new Date().getTime() + '-' + (++cid);
```

This should fix the issue. What do you think?

**Comment by codedward** [comment]
I actually looked into creating a proper GUID (via the javascript [here](http://stackoverflow.com/a/2117523/892420) which is totally awesome!), but there was something that expected the id of the columns to be an integer, possibly for sorting.

Using just `new Date().getTime()` should work, right?

**Comment by elenatorro** [comment]
Hi @codedward , thanks for reporting this issue, I had the same problem! I think using the date is a good solution right now, I'll be thinking about it.

**Comment by sdorra** [comment]
Should be fixed with 3896c4ae
