### ISSUE TITLE
Add support for SCSS syntax for styles

### ISSUE THREAD

**Issue by raulgomis** [angular-dashboard-framework/angular-dashboard-framework#149]
It would be great to have SASS preprocessor (with SCSS syntax) for styles in order to have:
- Nested syntax
- Ability to define variables
- Ability to define mixins
- Mathematical functions
- Operational functions (such as “lighten” and “darken”)
- Joining of multiple files
- etc.

**Comment by sdorra** [comment]
I'm not a great fan of SASS, because of the fact that the preprocessor requires ruby. What do you think about LESS? I've much more experience with LESS than SASS.

**Comment by raulgomis** [comment]
Hi @sdorra! There is a port called 'libsass' which is developed in C/C++ making SASS faster and easy to integrate (and of course, there is no need of ruby in the build system :) ). I see great future on SASS, lots of companies are moving from LESS to SASS: Even Bootstrap has announced that it will move to SASS in v4 http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/ so it would be great also that adf is compatible also with Bootstrap preprocessing in the future version of Bootstrap.

In order to integrate it with Node for the build system we should use the https://github.com/sass/node-sass module which is the wrapper of the libsass for Node, works quite well. What do you think? I could prepare a PR and we see how it seems.

**Comment by sdorra** [comment]
Ok, node-sass sounds good. A PR would be great.

**Comment by sdorra** [comment]
Fixed with pr #167
