### ISSUE TITLE
Add Logic to Apply button on Edit Form

### ISSUE THREAD

**Issue by pafq** [angular-dashboard-framework/angular-dashboard-framework#152]
Hi.

It is possible to add some code to the button apply on Edit Form?
I want to validate if all field are fill right.

If possible, how?

Thanks,
kintas

**Comment by sdorra** [comment]
Sorry, this currently not possible. But we will try to create a way for the next release.

**Comment by sdorra** [comment]
The main implementation is done in a separate [branch](https://github.com/angular-dashboard-framework/angular-dashboard-framework/tree/feature/152-apply-fn). But we should add annotation support for the apply method with [ng-annotate](https://github.com/olov/ng-annotate).

The apply function can be used as follow:
```javascript
dashboardProvider
  .widget('mywidget', {
    title: 'My Widget',
    description: 'My Awesome widget',
    templateUrl: '{widgetsPath}/mywidget/src/view.html',
    edit: {
      templateUrl: '{widgetsPath}/mywidget/src/edit.html',
      apply: function($http, config){
        // do something useful and return a boolean or a promise
        return true;
      }
    }
  });
```

**Comment by sdorra** [comment]
[Pull request](https://github.com/olov/ng-annotate/pull/222) on ng-annotate is open and the branch is merged.
