### ISSUE TITLE
Change Templates

### ISSUE THREAD

**Issue by trollr** [angular-dashboard-framework/angular-dashboard-framework#175]
Is it possible to change the standard templates eg. dashboard-title.html? 
Looked around, but found no possibility. 

Would be glad if you could help me :)

**Comment by sdorra** [comment]
Please have a look at [sample-03](https://github.com/angular-dashboard-framework/angular-dashboard-framework/blob/master/sample/scripts/sample-03.js), it uses different templates for the title and the add widget dialog.
