### ISSUE TITLE
Is there an auto refresh for widget?

### ISSUE THREAD

**Issue by andy-leung-hs** [angular-dashboard-framework/angular-dashboard-framework#177]
Can anyone help or guide me on how to get auto refresh working for widgets? I want the widgets to refresh at a certain interval (let's say every minute).

**Comment by nunos7** [comment]
Hi, see code of widget clock.
https://github.com/angular-dashboard-framework/adf-widget-clock/blob/master/src/clock.js#L57

In your case you can put a field in your edit widget to get the timer in seconds and then in the widget controller define a interval to run the refresh at that interval.

NS

**Comment by andy-leung-hs** [comment]
I should have been a little bit more clearer on my use case. I want to perform an ajax call every minute which occurs in my service. There is a resolver in the dashboardProvider but I don't understand how to trigger it. I pulled this from the adf-widget-weather example. 

````
        resolve: {
          data: function(weatcherService, config){
            if (config.location){
              return weatcherService.get(config.location);
            }
          }
        }
```

**Comment by sdorra** [comment]
You can't trigger a resolver from a widget. A resolver is loaded, when the widget is loaded. You have to call your service in a interval function e.g.:

```javascript
dashboardProvider
  .widget('my-widget', {
    title: 'My Widget',
    description: 'Displays my widget',
    templateUrl: '{widgetsPath}/my-widget/src/view.html',
    resolve: {
      data: function(myService){
        return myService.load();
      }
    },
    controller: function($scope, $interval, myService, data){
      // set the data from the resolve method
      $scope.data = data;

      // method to refresh your data
      function refresh(){
        $scope.data = myService.load();
      }

      // call refresh method every minute
      var promise = $interval(refresh, 60000);

      // cancel interval on scope destroy
      $scope.$on('$destroy', function(){
        $interval.cancel(promise);
      });
    }
  });
```
