### ISSUE TITLE
editTemplateUrl and addTemplateUrl are working?

### ISSUE THREAD

**Issue by jftsaraiva** [angular-dashboard-framework/angular-dashboard-framework#179]
HI,

I'm following [Sample-03](https://github.com/angular-dashboard-framework/angular-dashboard-framework/blob/master/sample/scripts/sample-03.js) and add my custom `titleTemplateUrl` and `editTemplateUrl`. 

The `titleTemplateUrl` is working well, but `editTemplateUrl` doesn't. 

Even in demo site the [sample-03](http://angular-dashboard-framework.github.io/angular-dashboard-framework/#/sample/03) isn't working, for example the title of your `custom-dashboard-edit.html`is 

```<h4 class="modal-title">Dashboard Configuration</h4>```

but when we click in edit `Edit Dashboard` is the default title (Edit Dashboard) that is showed in modal header.

**Comment by klintznc** [comment]
Did you manage to fix this missing property on ADF framework @jftsaraiva  ?

**Comment by bigloupe** [comment]
Somethink like 
  // set our custom widget title template when widgets are added
   $scope.$on('adfWidgetAdded',function(event,name,model,widget){
     widget.editTemplateUrl="partials/custom-dashboard-editwidget.html";
   });
is problably missing ?

**Comment by jftsaraiva** [comment]
This is fixed in 0.11.0 

Thanks
