### ISSUE TITLE
Missing 'adf.structures.base?

### ISSUE THREAD

**Issue by idreeshaddad** [angular-dashboard-framework/angular-dashboard-framework#181]
In the wiki it says:

Add the dependency to your module:
angular.module('sample', ['adf', 'adf.structures.base']);

but 'adf.structures.base' module does not exist in the dist nor src versions of the code, am I missing something?

**Comment by jvwing** [comment]
[adf-structures-base](https://github.com/angular-dashboard-framework/adf-structures-base) is a separate dependency you need to reference in addition to angular-dashboard-framework.  If you are using bower to install it, specify `adf-structures-base` as the dependency.  Then you can reference the `adf.structures.base` angular module.

**Comment by idreeshaddad** [comment]
I'm new to bower, can you show me the command to define it as a dependency?

**Comment by jvwing** [comment]
If you are using [bower](http://bower.io/), you can install it with the following command:

    bower install adf-structures-base --save

But bower isn't necessary, you can also just download and include `angular-structures-base.js` or  `angular-structures-base.min.js` from the [dist files](https://github.com/angular-dashboard-framework/adf-structures-base/tree/master/dist).

**Comment by idreeshaddad** [comment]
Thank you.
