### ISSUE TITLE
are you or is anyone looking at updating to support the latest ui.bootstrap lib

### ISSUE THREAD

**Issue by fvanzile** [angular-dashboard-framework/angular-dashboard-framework#182]
ui.bootstrap has been updating it's directives to uib-xxxxx such as 'collapse is now deprecated. Use uib-collapse instead'.  are you or anyone looking at updating the dashboard framework to the new directives?
thank you
Frank

**Comment by sdorra** [comment]
Version 0.11.0 uses angular-bootstrap 0.14.x with uib-...
