### ISSUE TITLE
ng-class in widget.html not compatible with Angular 1.2 and 1.3

### ISSUE THREAD

**Issue by ClementRivaille** [angular-dashboard-framework/angular-dashboard-framework#187]
Since the adding of styleClass to widgets definition, the div containing widgets in *windget.html* is written like this:
```html
<div adf-id="{{definition.wid}}" adf-widget-type="{{definition.type}}" ng-class="[{'panel panel-default':!widget.frameless || editMode},definition.styleClass]" class="widget">
```

The *ng-class* parameter used here is an array of objects. However, while this is compatible with Angular 1.4, in 1.2 and 1.3 ngClass only supports strings, objects, and arrays of strings.
This results in the classes *"panel panel-default"* not being applied at all.

For now the required version of angular is *">=1.2"*, but with this template, it strictly depends on 1.4. I guess one simple solution would be to update *bower.json*, but losing compatibility for one single line seems a little bit harsh.

To keep it compatible with lower versions of Angular, I would suggest to make one single ngClass object inside the controller. The ng-class in the template would become:
```html
ng-class="definition.styleClass"
```
And something like this should be added to *widget.js*:
```javascript
if (!definition.styleClass) {
  definition.styleClass = w.styleClass || {};
}
definition.styleClass['panel panel-default'] = !w.frameless || $scope.editMode;
```
Although this prevents the attribute to be dynamic. Maybe a $watch on *$scope.editMode* would be necessary?

**Comment by jvwing** [comment]
Good catch, @ClementRivaille.  When I added styleClass in [PR 171](https://github.com/angular-dashboard-framework/angular-dashboard-framework/pull/171), I did not test for compatibility with older versions of Angular.  Sorry about that.

I believe we need the dynamic nature of the mapping for `editMode`.  That makes sure the widget frame is visible while editing. I know $watch could cover this, but the solution starts being more complicated than I had hoped, anyways.

I propose reverting the styleClass feature until version compatibility is no longer an issue.  For me at least, there are workarounds involving the column classes and some tortured CSS.  It's not as elegant, but it works.
