### ISSUE TITLE
Where can i get API guide for Custom Widget ?

### ISSUE THREAD

**Issue by shravansofts** [angular-dashboard-framework/angular-dashboard-framework#198]
Where can i get API guide for Custom Widget ?
It will be very difficult using yo for each and every widget.
Please provide me link for adf.Provider.

**Comment by sdorra** [comment]
The documentation for the provider can be found [here](http://angular-dashboard-framework.github.io/angular-dashboard-framework/docs/#/api/adf.dashboardProvider).

**Comment by shravansofts** [comment]
Thanks for the help.
