### ISSUE TITLE
Add distributable js without widget templates

### ISSUE THREAD

**Issue by redwyre** [angular-dashboard-framework/angular-dashboard-framework#203]
Would it be possible to release a version that doesn't include the widget templates? We override them all so it's just dead weight for us. I did have a look at gulpfile.js but I'm a bit advanced for me at the moment.

**Comment by sdorra** [comment]
v0.12.0 will have the following release files:

* angular-dashboard-framework-tpls.js
* angular-dashboard-framework-tpls.min.js
* angular-dashboard-framework-tpls.min.js.map
* angular-dashboard-framework.css
* angular-dashboard-framework.js
* angular-dashboard-framework.min.css
* angular-dashboard-framework.min.js
* angular-dashboard-framework.min.js.map

**Comment by redwyre** [comment]
Thanks @sdorra, much appreciated.
