### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $uibModalProvider <- $uibModal <- adfDashboardDirective

### ISSUE THREAD

**Issue by sajjadROR** [angular-dashboard-framework/angular-dashboard-framework#206]
Error: [$injector:unpr] Unknown provider: $uibModalProvider <- $uibModal <- adfDashboardDirective
http://errors.angularjs.org/1.4.4/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20adfDashboardDirective
    at angular.js:68
    at angular.js:4284
    at Object.getService [as get] (angular.js:4432)
    at angular.js:4289
    at getService (angular.js:4432)
    at Object.invoke (angular.js:4464)
    at angular.js:7037
    at forEach (angular.js:336)
    at Object.<anonymous> (angular.js:7035)
    at Object.invoke (angular.js:4473)

Kindly guide me.

**Comment by jvwing** [comment]
It sounds like you might be missing the [UI-Bootstrap](https://angular-ui.github.io/bootstrap/) library.  Can you share how you are including the scripts?

**Comment by sajjadROR** [comment]
Included but that is not a problem
=====================
app.controller('dashboardController', [
    '$scope', function($scope) {
        $scope.message = 'Welcome To Dashboard.. InProgress';
        var dashboard_settings, data, model;

        data = {
            "ui_components": "'adf.widget.pieChart','adf.widget.stackedColumnChart','adf.widget.table'",
            "site_path": "http://localhost:8080",
            "current_user_dashboard_config": "{\"rows\":[{\"columns\":[{\"styleClass\":\"col-md-12\",\"widgets\":[{\"type\":\"stackedColumnChart\",\"config\":{},\"widget_id\":26,\"user_id\":12,\"$$hashKey\":null,\"title\":\"Project Status Bar Chart\",\"wid\":26}],\"$$hashKey\":\"object:113\",\"cid\":1}],\"$$hashKey\":\"object:107\"},{\"columns\":[{\"styleClass\":\"col-md-4\",\"widgets\":[],\"$$hashKey\":\"object:115\",\"cid\":2},{\"styleClass\":\"col-md-4\",\"widgets\":[],\"$$hashKey\":\"object:116\",\"cid\":3},{\"styleClass\":\"col-md-4\",\"widgets\":[],\"$$hashKey\":\"object:117\",\"cid\":4}],\"$$hashKey\":\"object:108\"}],\"title\":\"Dashboard\",\"structure\":\"12/4-4-4\",\"titleTemplateUrl\":\"../src/templates/dashboard-title.html\"}",
            "current_user_id": 12
        };

        $scope.dashboard = data;

        model = null;

        dashboard_settings = data.current_user_dashboard_config;

        if (dashboard_settings) {
            model = JSON.parse(dashboard_settings);
        }

        if (model === null) {
            model = {};
        }

        $scope.dashboard = {
            model: model
        };

    }
]);
=====================================
in html file

<div class="container" ng-controller="dashboardController">
    {{message}}
    <adf-dashboard name="sematreeDashboard" structure="4-8" adf-model="dashboard.model" editable="true"  />
</div>
