### ISSUE TITLE
Save config of the random message widget

### ISSUE THREAD

**Issue by boltex** [angular-dashboard-framework/angular-dashboard-framework#211]
When changing the title of the random (douglas adam) widget, it just errors "TypeError: Cannot read property 'apply' of undefined". 

You can see this on the live demo. 

I am trying to make my own widget and also to understand how widget work. How can I fix this?

**Comment by sdorra** [comment]
Ok, I'can reproduce the issue. I will try to look at this asap.

**Comment by sdorra** [comment]
Fixed.

**Comment by boltex** [comment]
got rid of the error message **but does not trigger "widgetConfigChanged" nor does it make it save the new title if the title was changed... **

**Comment by sdorra** [comment]
@boltex i've tested the fix and the title was saved. The missing event is the correct behaviour. The event is only fired if edit.reload=true.

**Comment by boltex** [comment]
Oh I just re-checked and you are right. I did not notice the "if (widget.edit && widget.edit.reload) {" part, 
Thank you! 
(I am making a project in  continuous-edit-mode="true" so i added some event to be broadcasted when things change) Thanks again!

**Comment by random-one** [comment]
Is the first part of #238 the same? My message was different but from the description it looks very familiar to me.
