### ISSUE TITLE
Can we integrate Fusion Chart with this framework ?

### ISSUE THREAD

**Issue by sharathbangera6** [angular-dashboard-framework/angular-dashboard-framework#212]
Hi,

I am using this dashboard for one of my work and i wanted to integrate fusion chart to this. I tried using it but somehow the chart doesn't load and i don't see any error. Is there any problem integrating fusion chart with this framework ?

Thank You
Sharath Bangera

**Comment by sdorra** [comment]
I don't know fusion chart, but i don't see any problems about this. You should be able to use [angular.js charts plugin of fusion chart](http://www.fusioncharts.com/angularjs-charts/).

**Comment by boltex** [comment]
As a tag it did not work, as a directive it worked for me!
... meaning that this way works : 
```
<div fusioncharts
    width="100%" 
    height="400"
    type="column2d"
    datasource="{{datasource}}"
    ></div>
```
but this way does not : 
```
 <fusioncharts 
    width="100%" 
    height="400"
    type="column2d"
    datasource="{{datasource}}"
    ></fusioncharts>
```

**Comment by sharathbangera6** [comment]
Can you please paste the full code here ? i am still not able to get it. 

[https://github.com/angular-dashboard-framework/angular-dashboard-framework/issues/213]

I have put my code here.

**Comment by boltex** [comment]
Better yet : https://github.com/boltex/adf-widget-fusiontest
