### ISSUE TITLE
Frameless and template error message

### ISSUE THREAD

**Issue by chule143** [angular-dashboard-framework/angular-dashboard-framework#216]
Hi, I'm new on this library, but I have an strange issue: when I copy the example and refreshed the page (with a cleaning the cache in Chrome) I see this message in the console:
```
Cannot read property 'frameless' of undefined widgetClasses
and 
Cannot read property 'template' of undefined
could not find widget
```
And the widgets are not rendered
But when I update the page again the message dissapear

**Comment by heenaI** [comment]
@chule143 were you able to find a solution to this problem? I am having a similar error. could you locate what is the source of this problem

**Comment by sdorra** [comment]
It looks like you have an widget in your model, with an unknown type. I will try to show an proper error message for this problem.
