### ISSUE TITLE
Newbie Question??

### ISSUE THREAD

**Issue by dharanid** [angular-dashboard-framework/angular-dashboard-framework#218]
HI,

I'm very new to this Dashboard Framework.
In Edit Mode I created a separate template by using following config
edit: {
          template: require("./widgetedit.html"),
          reload: false,
          controller: WidgetEditController
        }

i want to override the default submit method calling from library in my config.

please let me know how to do it

Thanks
Dharani

**Comment by sdorra** [comment]
You can override the default submit logic by using a custom apply function e.g.:

```javascript
edit: {
  template: "./widgetedit.html",
  reload: false,
  controller: WidgetEditController,
  apply: function(){
    // your logic
  }
}
```
