### ISSUE TITLE
How to prevent reloading all the widgets when just adding one

### ISSUE THREAD

**Issue by boltex** [angular-dashboard-framework/angular-dashboard-framework#223]
Hello again! 

Is there a way to prevent all the widgets to refresh when I just add one to the dashboard?

Many thanks in advance!!

**Comment by sdorra** [comment]
The widgets should not reload, after adding a widget to the dashboard. Could you describe this behaviour in more detail?

**Comment by boltex** [comment]
Nevermind, i override the widget creation process and i caused this issue.
