### ISSUE TITLE
Observing $scope.adfModel

### ISSUE THREAD

**Issue by chule143** [angular-dashboard-framework/angular-dashboard-framework#226]
Hi, first thanks for this great library :)

I want to know how to observe the $scope.adfModel or there is any $rootscope for that model?, I need to watch the collection to auto save on any action in the dashboard.

**Comment by mohan-gundlapalli** [comment]
There is an event  adfDashboardChanged which gets fired when the dashboard is changed. you can subscribe to the event the following way and save your model.

$scope.$on('adfDashboardChanged', function (event, name, model) {
            localStorageService.set(name, model);
        });
