### ISSUE TITLE
More intuitive format of dashboard-edit.html

### ISSUE THREAD

**Issue by bennettatoms** [angular-dashboard-framework/angular-dashboard-framework#233]
Thank you for your work on this module! I've really enjoyed working with it.

This is not an issue, really, and I saw there was recently a pull request addressing this a different way, but I thought a small improvement to adf would be to display the structures in the dashboard-edit modal in a more visually informative way than just listing the row/column widths like `12/4-4-4` and `3-9 (12/6-6)`, so [I created this gist](https://gist.github.com/bennettatoms/8c7b9f6c639b87e3342701c1b6dbb436). It's not the heartiest code, but it works with the base.js structures. The results are below.

<img width="905" alt="screenshot 2016-04-08 12 50 36" src="https://cloud.githubusercontent.com/assets/8884052/14391261/fae6b38e-fd88-11e5-849d-b4f8d81513eb.png">

Feel free to use, if you like.

**Comment by sdorra** [comment]
Thanks, i will have a look at it soon.

**Comment by sdorra** [comment]
Hi, thanks for the issue and you gist. But i've decided to use an other approach to implement the structure preview:

<img width="908" alt="screen shot 2016-05-13 at 22 47 43" src="https://cloud.githubusercontent.com/assets/493333/15297529/ee92b65c-1b9a-11e6-8e9c-6c12da798fad.png">

Your gist was a big help for this implementation, Thanks.

**Comment by bennettatoms** [comment]
Looks great! I'll update with your implementation :)
