### ISSUE TITLE
w.edit is undefined, adf-dashboard-content shows unnecessary loading progress

### ISSUE THREAD

**Issue by random-one** [angular-dashboard-framework/angular-dashboard-framework#238]
Hello,

I got into following issue with the latest relase of ADF. When I open the edit dialog of a widget, that is configured without an edit section in its definition I get following error message in the console:
```
Error: t.edit is undefined
l/o.edit/a.saveDialog@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/sample-88ee209215.min.js:9:4906
anonymous/fn@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js line 4 > Function:2:218
Ho[t]</<.compile/</</i@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js:5:5882
vn/this.$get</p.prototype.$eval@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js:3:5601
vn/this.$get</p.prototype.$apply@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js:3:5830
Ho[t]</<.compile/</<@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js:5:5932
We/n@http://angular-dashboard-framework.github.io/angular-dashboard-framework/js/angular-1faf36c388.min.js:1:16341
```
This is the error when I edit the title of the randommsg widget in sample-01 of the online demo. For my widget the error is similar. The common between both widgets is that they both do not define edit section in their definitions. According to the documentation the edit part is not required.

I decided to fix this by altering following lines in the ```provider.js```:
```
this.widget = function(name, widget){
      var w = angular.extend({reload: false, frameless: false}, widget);
      if ( w.edit ){
        var edit = {
          reload: true,
          immediate: false,
          apply: defaultApplyFunction
        };
        angular.extend(edit, w.edit);
        w.edit = edit;
      }
      widgets[name] = w;
      return this;
    };
```
to:
```
    this.widget = function(name, widget){
      var w = angular.extend({reload: false, frameless: false}, widget);
      var edit = {
        reload: true,
        immediate: false,
        apply: defaultApplyFunction
      };
      angular.extend(edit, w.edit || {});
      w.edit = edit;
      widgets[name] = w;
      return this;
    };
```
So that the ```widget.edit``` is not undefined anymore. This seems to fix the problem.

Then my second issue is when opening the edit dialog of the same widget the ```adf-dashboard-content``` directive renders the loading progress in the edit dialog for some reason. What I did not understand is why do we use the same ```adf-widget-content``` directive both to display the widget and to render it's edit dialog. Here is a screenshot:
![loading-progress](https://cloud.githubusercontent.com/assets/1182092/14704930/d6805f04-07bf-11e6-8c9b-433a9bb9ef20.png)

**Comment by sdorra** [comment]
The bug seems to be fixed with the upcoming version.
