### ISSUE TITLE
Filter Add Widget List

### ISSUE THREAD

**Issue by c5racing** [angular-dashboard-framework/angular-dashboard-framework#242]
I want to provide a number of widgets but filter the list by user rights.  Is there an example of pulling the list of widgets or otherwise filtering the list of available widgets from a web service?

**Comment by sdorra** [comment]
You could implement a widget filter. Please have a look at [sample 3](https://github.com/angular-dashboard-framework/angular-dashboard-framework/blob/master/sample/scripts/sample-03.js#L71).
