### ISSUE TITLE
Can you add license for the adf-structrue-base and all the widgets?

### ISSUE THREAD

**Issue by JeremyLi28** [angular-dashboard-framework/angular-dashboard-framework#243]
Hi, 

I'm using WebJar to import you library to my Scala/Play project, angular-dashboard-framework can be successfully imported because it has MIT license, but structure-base and other widgets can't. Can you add MIT license to all the repo so that any JVM based projects using WebJar can successfully import your library?

Thanks
Chen

**Comment by sdorra** [comment]
done.
