### ISSUE TITLE
Sharing ReadOnly Items between widgets

### ISSUE THREAD

**Issue by ashishtilara** [angular-dashboard-framework/angular-dashboard-framework#244]
Hi I am creating custom set of widgets, and requirement is there is list of properties that comes from database and all widgets needs them, is there a way I can set Dashboard level config that is accessible in widgets?

Thank you,
Ashish

**Comment by ashishtilara** [comment]
Is it possible to add - editController, so I can inject custom factory/service?

**Comment by sdorra** [comment]
Do you mean an edit controller for a widget? Please have a look at the [api of the dashboard provider](http://angular-dashboard-framework.github.io/angular-dashboard-framework/docs/#/api/adf.dashboardProvider).

**Comment by ashishtilara** [comment]
@sdorra thats exactly what I was looking for, Thank you so much!

Is there a plan on adding gridster support as well as putting this on NPM?

Thank you very much for the awesome project btw. 😄

**Comment by sdorra** [comment]
Gridster support is not planned at the moment, but pull requests are welcome 😉 

NPM is planned, but their are some problems at the moment [#252](https://github.com/angular-dashboard-framework/angular-dashboard-framework/issues/252).
