### ISSUE TITLE
Define templates directory through dashboardProvider

### ISSUE THREAD

**Issue by marcoT89** [angular-dashboard-framework/angular-dashboard-framework#250]
Congratulations for your excellent job dude!! This is a great project!

I'd like to know if it's possible to change the 'adfTemplatePath' to my own custom templates directory? I didn't find it. Maybe use a method like 'setTemplatePath' in dashboardProvider?

What do you think?

Thanks

**Comment by pdemilly** [comment]
A quick workaround is

angular.module ('adf').value ('adfTemplatePath', 'mysrc/templates/');

**Comment by sdorra** [comment]
The workaround of @pdemilly should do the job.

**Comment by eppak** [comment]
@pdemilly 

Excuse me, the workaround have to be done on the sources? Or i can do it in the int like:

`angular.module('sample', [
  'adf', 'adf.structures.base', 'adf.widget.news',
  'adf.widget.randommsg', 'adf.widget.weather',
  'adf.widget.markdown', 'adf.widget.linklist',
  'adf.widget.github', 'adf.widget.version',
  'adf.widget.clock', 'adf.widget.travis',
  'LocalStorageModule',
  'sample-01', 'sample-02', 'sample-03',
  'sample-04', 'sample-05', 'ngRoute'
])
.value ('adfTemplatePath', 'mysrc/templates/')
.config(function(dashboardProvider, $routeProvider, localStorageServiceProvider){`

Thanks
