### ISSUE TITLE
npm package has invalid dependencies

### ISSUE THREAD

**Issue by justingish** [angular-dashboard-framework/angular-dashboard-framework#252]
I'm not sure if this is the right place to file this bug, but when trying to install this package from npm, I get several errors about dependencies not existing or not having a compatible version.  

The first one I ran into was Sortable.  Apparently npm doesn't allow uppercase letters in the package names anymore. Then angular-bootstrap didn't have a compatible version.  There may be others as well.

**Comment by sdorra** [comment]
The angular-dashboard-framework version, which is hosted on npm is **not** the official version. It is not hosted by a team member. I've already contact the uploader and the npm team for a removal of that version. I hope that we can publish the official version soon.

**Comment by justingish** [comment]
Oh, that makes more sense.  Thanks!
