### ISSUE TITLE
Where is the glyphicon-edit icon located

### ISSUE THREAD

**Issue by heenaI** [angular-dashboard-framework/angular-dashboard-framework#254]
Hi,
I have been trying to figure out where is the edit icon that opens up edit options is located. I can find the all other icons for edit options under custom-dashboard-title.html but cannot the place where the edit icon itself is located

**Comment by sdorra** [comment]
All icons of adf a part of the [glyphicon icon font](http://getbootstrap.com/components/#glyphicons-glyphs). The edit icon is called glyphicon-edit.

**Comment by kirankamana** [comment]
Hi,
I would like to replace ex: glyphicon glyphicon-off icon in place of glyphicon-edit icon.
I have tried to see where exactly to change the code. please guide us where i have to change the snippet.
Thank you
