### ISSUE TITLE
How do i access the checkbox value which is in Edit form in the directive of widget ?

### ISSUE THREAD

**Issue by sharathbangera6** [angular-dashboard-framework/angular-dashboard-framework#255]
I have used a checkbox in my widget edit form, on check/uncheck of it and clicking on apply, i want the value to be passed to the widget directive. How do i do that ? i tried following : 

```
   <div class="checkbox">
        <label class="showLabel"><input type="checkbox" value="" name="check" ng-click="showLogo=!showLogo" ng-model="config.showLogo"/>Show Logo</label>
    </div>
```

in the controller tired , console.log($scope.showLogo) // undefined.

**Comment by sdorra** [comment]
You have to inject the config object into your controller e.g.:

```javascript
function ContentController(config){
  console.log(config.showLogo);
}
```
