### ISSUE TITLE
Is there way to open new tab on click on any element?

### ISSUE THREAD

**Issue by amod2005** [angular-dashboard-framework/angular-dashboard-framework#256]
Hi, 
Thanks for this wonderful framework. Is there way I can open up a tab on click of <tr> inside of dashboard? I saw example of adf-dynamic-example-master but it shows opening up new tab on tab click. Want to achieve this by click of an table row inside tab 1 or so. 

Also is it possible to send values along with click?

**Comment by sdorra** [comment]
I think you are looking for a router like [ng-route](https://docs.angularjs.org/api/ngRoute) or [ui-router](https://github.com/angular-ui/ui-router).
