### ISSUE TITLE
when i operate "Add New Widget" of sample 01, it goes error

### ISSUE THREAD

**Issue by honjay88** [angular-dashboard-framework/angular-dashboard-framework#257]
I'm test a function of example "Add New Widget in sample01", it can not add new one, and the error is like below picture.How can I do it, please help my question ,thanks!!

![image](https://cloud.githubusercontent.com/assets/14837073/16663272/16abc084-44ae-11e6-9323-8657dfe77034.png)

**Comment by rooterkyberian** [comment]
as for workarounds - disabling (removing) `categories="true"` worked for me
