### ISSUE TITLE
Localization of user generated content

### ISSUE THREAD

**Issue by justingish** [angular-dashboard-framework/angular-dashboard-framework#261]
Our use case may be a bit different from others so let me quickly explain it.  We allow administrators on our site to create dashboards that will be viewed by other non-admin users.  The admin user gets to set up all the widgets and customize the content and the non-admin users just consume the information.  I have created several widgets that allow for user generated content (like simple messages and news bulletins).  We need to be able to localize this user-generated content.

My first thought would be to modify the edit template of the widgets to have a droplist of supported culture codes, so that when they enter the data, they could enter it in all languages that they care about.  We would then just need to store the data in a way that it knows which culture code it belong to.  Then when the end user is viewing the widget it would determine which content to show based on the logged in user's culture code.

Has anyone else attempted anything like this? Does anyone have any ideas that might help (preferably without forking the framework)? If there isn't a good way to accomplish withing the framework, we might be willing to extend the framework if it would be beneficial to others.

**Comment by sdorra** [comment]
You should be able to do this, without extending or fork the framework. You can easily add a i18n switcher in the edit part of your widgest and store the entered content in several languages. I don't think that this is related to the framework, it is more related to your widgets.

**Comment by justingish** [comment]
Good point, that would work for any custom content in the widgets themselves.  I guess I was mostly just confused about how I would handle the Title field that is built in to every widget's edit template.  But I suppose if I created a custom widget template I could put the i18n switcher in as part of our base widget template and then I could handle both the title and anything custom to the widget.

I'll have to give that a shot soon and see how it goes.  Thanks for the suggestion.
