### ISSUE TITLE
Question Angular 2

### ISSUE THREAD

**Issue by geneeblack** [angular-dashboard-framework/angular-dashboard-framework#270]
Any plans to port this to Angular 2? It's a great reference project but I'm just learning Angular 2 and am not ready to attempt to port this myself. It would be a great resource though.

**Comment by raulgomis** [comment]
Hi @geneeblack, this question was already raised some time ago: #214. Let's use the other thread to discuss about the migration to Angular 2.

**Comment by raulgomis** [comment]
@geneeblack could you close this issue, please?

**Comment by sdorra** [comment]
Duplicate of #214
