### ISSUE TITLE
Widget Id

### ISSUE THREAD

**Issue by nahuelramos** [angular-dashboard-framework/angular-dashboard-framework#272]
Hi,
I need to know if the WID is unique for each widget

thanks.

**Comment by raulgomis** [comment]
it should be unique to get the references in order to sort the dashboards, etc.
This is the function that generates the WID: https://github.com/angular-dashboard-framework/angular-dashboard-framework/blob/b2002b64013e54b78eac251df0672bd5d6a83aa7/src/scripts/provider.js#L336

**Comment by nahuelramos** [comment]
Thank you!
