### ISSUE TITLE
Small refactor to meet some angularjs code style best practices

### ISSUE THREAD

**Issue by raulgomis** [angular-dashboard-framework/angular-dashboard-framework#273]
It would be great to perform a small refactor to meet some angular coding recommended practices. Specially if we go for Angular 2 #214 migration. Some example could be:
- Name files with the recommended pattern: feature.type.js. As it provides a consistent way to quickly identify components.
- Separate some directives logic into services in order to be easier to test. 
- etc.

@sdorra if you agree I could code a first refactoring proposal.

More details could be found in Jonh Papa angular-styleguide: https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#directive-component-names

**Comment by sdorra** [comment]
Yes, i agree completely with it and i'm a big fan of the styleguide from John Papa.
