### ISSUE TITLE
Not able to set modal width to addWidgetDialog indepened to remove

### ISSUE THREAD

**Issue by Jst10** [angular-dashboard-framework/angular-dashboard-framework#291]
Hi,

I am trying to set width to modal which open on adding widget on dashboard. I can achieve this with css when I set  width to element with class `.modal-dialog`. But when I do this I break modal for removing widget from dashboard (confirmation dialog).

I didn't found any solution for this so I think that this can't be done?

I propose that you add additional classes to this modals when you open them so that we could select them independently and define ours styles to them.

Like this:
```
 var opts = {
              scope: deleteScope,
              templateUrl: deleteTemplateUrl,
              windowClass: 'remove-widget-modal'
              backdrop: 'static'
            };
```

I think that this would solve my problems.

**Comment by mindscratch** [comment]
see pull request [316](https://github.com/angular-dashboard-framework/angular-dashboard-framework/pull/316) which would let you set the modal size (`sm`, `md`, `lg`).
