### ISSUE TITLE
readColumns() return wrong column size when column has rows

### ISSUE THREAD

**Issue by swangui** [angular-dashboard-framework/angular-dashboard-framework#293]
for example, the following layout will fail in remaining the order of widgets
3-9 (12/6-6) column size calculated as 6 (should be 5, 1 of them is used for structuring purpose only)
2-10 (12/6-6/12) column size calculated as 5 (should be 4, 1 of them is used for structuring purpose only)

but these are fine
12/4-4-4 column size calculated as 4
4-8 column size calculated as 2
6-6 column size calculated as 2

**Comment by samuelwang48** [comment]
Closed due to wrong github account being used
